// Pre-authored, always-on interactive Sage demos that ship with the book
// ("in-built applets"), sourced from the SageCell usage on
// crypto.katestange.net. Each is injected as an editable SageCell immediately
// after the block with id `xmlId` when its chapter loads (see
// ReadingPane.injectBuiltinApplets). If an `xmlId` isn't in the current build,
// that applet is silently skipped, so this list is safe to edit freely.
//
// The `code` runs on the public SageCell server (Sage 10.x). Keep each demo
// small, self-contained, visibly output-producing, and pleasant to tweak --
// the comments point a student at the one or two values worth changing.

export const builtinApplets = [
  {
    // §1.5 Key Exchange — modular exponentiation as a mixing map.
    xmlId: 'S1.SS5.SSS1.p2',
    title: 'Try it — modular exponentiation as a mixing map',
    tool: 'sage',
    code: `# Each residue x mod n is wired to x^a mod n. This "mixing" is what
# makes modular exponentiation useful for key exchange.
# Try changing n (the modulus) and a (the exponent), then press Run.
n = 7
a = 2
R = IntegerModRing(n)
left  = [' ' + str(r) + ' '  for r in R]
right = ['  ' + str(r) + '  ' for r in R]
pre_pos = graphs.CompleteBipartiteGraph(len(left), len(right)).get_pos()
G = DiGraph()
pos = {}
for (i, v) in enumerate(left + right):
    G.add_vertex(v)
    pos[v] = pre_pos[i]
for x in range(n):
    G.add_edge(left[x], right[lift(R(x ^ a))])
G.plot(pos=pos)`
  },
  {
    // §5.1 Elliptic curves — the chord-and-tangent addition law, constructed
    // interactively in GeoGebra. NOTE: GeoGebra command syntax is best
    // verified in the live applet; drag A and B along the curve.
    xmlId: 'S5.SS1.p12',
    title: 'Try it — adding two points P + Q on an elliptic curve',
    tool: 'geogebra',
    code: `# y^2 = x^3 - 3x + 5. Drag P and Q along the curve; P+Q is built by
# the chord-and-tangent law: line PQ meets the curve at a third point R,
# then reflect R over the x-axis. R is found algebraically (the three
# x-coordinates on the line sum to the slope squared).
c: y^2 = x^3 - 3x + 5
P = Point(c)
Q = Point(c)
line1 = Line(P, Q)
t = (y(Q) - y(P)) / (x(Q) - x(P))
u = t^2 - x(P) - x(Q)
v = t*(u - x(P)) + y(P)
R = (u, v)
Sum = (u, -v)
vLine = Line(R, yAxis)
SetCaption(Sum, "P+Q")
SetColor(c, "Black")
SetColor(P, "#1a7f37")
SetColor(Q, "#0969da")
SetColor(line1, "#8250df")
SetColor(R, "#bf8700")
SetColor(vLine, "#bf8700")
SetColor(Sum, "#cf222e")
SetPointSize(P, 5)
SetPointSize(Q, 5)
SetPointSize(R, 5)
SetPointSize(Sum, 6)`
  },
  {
    // §7.2 Lattices — the lattice generated by the book's basis vectors,
    // drawn with an interactive Desmos graph.
    xmlId: 'S7.SS2.p7',
    title: 'Try it — the lattice generated by v₁ = (17, 5), v₂ = (19, 10)',
    tool: 'desmos',
    code: `# The lattice L = a·v1 + b·v2 over all integers a, b in [-6, 6].
# Edit 17, 5, 19, 10 to any numbers and watch the lattice change.
# (a, b run over a 13x13 grid, flattened via one index list N.)
N = [0, ..., 168]
a = mod(N, 13) - 6
b = floor(N / 13) - 6
(17 a + 19 b, 5 a + 10 b)
(17, 5)
(19, 10)`
  },
  {
    // §8.5 Linear codes — the [7,4] binary Hamming code, and 1-error decoding.
    xmlId: 'S8.SS5.p1',
    title: 'Try it — the [7,4] Hamming code corrects one error',
    tool: 'sage',
    code: `# A linear code: the [7, 4] binary Hamming code.
# Try flipping a different bit below, or GF(2) -> GF(3), then press Run.
C = codes.HammingCode(GF(2), 3)
print("Code:", C)
print("length =", C.length(),
      " dimension =", C.dimension(),
      " minimum distance =", C.minimum_distance())
print()
print("Generator matrix:")
print(C.generator_matrix())
print()

# Encode a 4-bit message, corrupt one bit, and watch the code recover it.
message  = vector(GF(2), [1, 0, 1, 1])
codeword = message * C.generator_matrix()
received = copy(codeword)
received[2] += 1          # <-- flip any single bit (index 0..6)

print("message  =", message)
print("codeword =", codeword)
print("received =", received, "  (1 bit flipped)")
print("decoded  =", C.decode_to_message(received))`
  }
];
